### ISSUE TITLE
[BUG] Error fetching linked users from the API

### ISSUE THREAD

**Issue by Dino-log** [anditv21/panel#126]
Value error: Invalid response format: 'status' not found or not 'success'
2023-09-09 16:46:30 ERROR    discord.ext.tasks Unhandled exception in internal background task 'bg_task'.
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/home/container/bot.py", line 64, in bg_task
    linked_users_response = await get_linked_users()
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/functions.py", line 65, in get_linked_users
    raise ValueError("Invalid response format: 'status' not found or not 'success'")
ValueError: Invalid response format: 'status' not found or not 'success'
2023-09-09 16:50:48 ERROR    discord.client Attempting a reconnect in 1.25s
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/discord/client.py", line 659, in connect
    await self.ws.poll_event()
  File "/home/container/.local/lib/python3.11/site-packages/discord/gateway.py", line 646, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000

**Comment by anditv21** [comment]
Make sure the bot and the API are on the same server, as it won't accept requests from different IPs. Check that you've set up the panel correctly using setup.php. Also, double-check the config.json file to ensure it's configured correctly.

**Comment by anditv21** [comment]
Since no further answers were added by the author, this issue is now treated as completed.
